name: Update README with Now Playing
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with now playing
        run: |
          now_playing=$(cat now_playing.md)
          # Replace placeholder <!-- NOW_PLAYING --> in README.md with content of now_playing.md
          sed -i "/<!-- NOW_PLAYING -->/{
            N
            s/<!-- NOW_PLAYING -->.*<!-- END_NOW_PLAYING -->/<!-- NOW_PLAYING -->\n$now_playing\n<!-- END_NOW_PLAYING -->/
          }" README.md
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "Update now playing status"
            git push
          else
            echo "No changes to commit"
          fi
